name: Windows Release

on:
  push:
    tags:
    - '*'    

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set Version Package Json
        run: cd ${{ github.workspace }} && set RELEASE_VERSION=${GITHUB_REF#refs/*/} && powershell ./buildversion.ps1        
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 21.7.1

      - name: Install Dependencies
        run: npm install
    
      - name: Publish
        run: npm run publish
  
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/make/squirrel.windows/x64/*.exe,out/make/*.dmg,out/make/**/*.deb"
